# -*- coding: utf-8 -*-
"""API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14PRdYjhhqSrzsZYWdbJw3AuJz_TyJjRT
"""

# Api handeling in python

import requests
import pandas as pd
def get_api_data():
  response = requests.get('https://jsonplaceholder.typicode.com/posts/1')
  data = response.json()
  print(data)
  df = pd.DataFrame([data])
  print(df)
  print(df.shape)
get_api_data()

import requests
import pandas as pd


API_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

city = "Jaipur"

url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"

response = requests.get(url)

data = response.json()


print(data)

if data["cod"] == 200:

    print("\n====== WEATHER DETAILS ======")

    print("City:", data["name"])
    print("Country:", data["sys"]["country"])

    print("Temperature:", data["main"]["temp"], "°C")
    print("Feels Like:", data["main"]["feels_like"], "°C")

    print("Humidity:", data["main"]["humidity"], "%")

    print("Weather:", data["weather"][0]["main"])
    print("Description:", data["weather"][0]["description"])

    print("Wind Speed:", data["wind"]["speed"], "m/s")

    print("=============================")

else:
    print("Error:", data["message"])

import requests
import pandas as pd

API_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

cities = ["Delhi", "Mumbai", "Jaipur", "Kolkata"]

weather_data = []

for city in cities:

    # API URL
    url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"

    response = requests.get(url)


    data = response.json()


    if data["cod"] == 200:


        weather_data.append({
            "City": data["name"],
            "Country": data["sys"]["country"],
            "Temperature (°C)": data["main"]["temp"],
            "Feels Like (°C)": data["main"]["feels_like"],
            "Humidity (%)": data["main"]["humidity"],
            "Weather": data["weather"][0]["main"],
            "Description": data["weather"][0]["description"],
            "Wind Speed (m/s)": data["wind"]["speed"]
        })

    else:
        print(f"Error fetching data for {city}")

df = pd.DataFrame(weather_data)

print(df)
print("\n")
print(df.shape)
