# -*- coding: utf-8 -*-
"""SqLite3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3-XX5NjLDihpO7HOM_QRPppT4PNSaX3
"""

import sqlite3
import random
import pandas as pd
import numpy as np
import os


def fetch_data_from_database():

    # Define the database file name
    db_file = 'example.db'

    # Remove the database file if it exists to prevent 'database is locked' errors
    if os.path.exists(db_file):
        os.remove(db_file)

    # Connect database
    conn = sqlite3.connect(db_file)

    # Create cursor
    cursor = conn.cursor()

    # Drop the table if it already exists to ensure a fresh start (redundant after file removal but harmless)
    cursor.execute('DROP TABLE IF EXISTS users')

    # Create table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS users(
            id INTEGER PRIMARY KEY,
            name TEXT,
            age INTEGER
        )
    ''')

    # Insert 20 records
    for i in range(1, 21):

        name = f"Student_{i}"
        age = random.randint(18, 30)

        cursor.execute(
            "INSERT INTO users (id, name, age) VALUES (?, ?, ?)",
            (i, name, age)
        )

    # Save changes
    conn.commit()

    # Fetch data
    cursor.execute("SELECT * FROM users")

    rows = cursor.fetchall()

    # Convert to DataFrame
    df = pd.DataFrame(rows, columns=['id', 'name', 'age'])

    # Add a 'marks' column with random integers between 50 and 100
    df['marks'] = np.random.randint(50, 101, len(df))

    # Print output
    print(df)

    # Close connection
    conn.close()

    return df


# Call function and store the result in 'df'
data = fetch_data_from_database()

data_sorted_by_age = data.sort_values(by='age', ascending=True)
display(data_sorted_by_age)

mean_price = data["marks"].mean()

print("Mean Price:", mean_price)

marks_above_mean = data[data['marks'] > mean_price]
display(marks_above_mean)

"""**Tabel of Students.**

### Create a new SQL database with 100 rows and custom columns
"""

import sqlite3
import random
import pandas as pd
import numpy as np
import os

def create_new_database():
    db_file = 'new_example.db'
    if os.path.exists(db_file):
        os.remove(db_file)

    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()

    cursor.execute('DROP TABLE IF EXISTS students')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS students(
            id INTEGER PRIMARY KEY,
            name TEXT,
            course TEXT,
            cgpa REAL,
            email_id TEXT
        )
    ''')

    courses = ['Computer Science', 'Electrical Engineering', 'Mechanical Engineering']

    for i in range(1, 101):
        name = f"Student_{i}"
        course = random.choice(courses)
        cgpa = round(random.uniform(2.0, 4.0), 2)
        email_id = f"student{i}@example.com"

        cursor.execute(
            "INSERT INTO students (id, name, course, cgpa, email_id) VALUES (?, ?, ?, ?, ?)",
            (i, name, course, cgpa, email_id)
        )

    conn.commit()
    cursor.execute("SELECT * FROM students")
    rows = cursor.fetchall()
    df_new = pd.DataFrame(rows, columns=['id', 'name', 'course', 'cgpa', 'email_id'])
    conn.close()
    return df_new


new_student_data = create_new_database()
display(new_student_data.head())

"""Here is the head of the newly created database table.

### Create a new SQL database for faculty with 3 rows
"""

import sqlite3
import random
import pandas as pd
import os

def create_faculty_database():
    db_file = 'faculty.db'
    if os.path.exists(db_file):
        os.remove(db_file)

    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()

    cursor.execute('DROP TABLE IF EXISTS faculty')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS faculty(
            id INTEGER PRIMARY KEY,
            name TEXT,
            assigned_subject TEXT,
            experience INTEGER,
            salary REAL
        )
    ''')

    subjects = ['Computer Science', 'Electrical Engineering', 'Mechanical Engineering']

    faculty_data = [
        ("Dr. Alice Smith", random.choice(subjects), random.randint(5, 20), round(random.uniform(60000, 120000), 2)),
        ("Dr. Bob Johnson", random.choice(subjects), random.randint(3, 15), round(random.uniform(50000, 100000), 2)),
        ("Dr. Carol White", random.choice(subjects), random.randint(10, 25), round(random.uniform(70000, 150000), 2))
    ]

    for i, (name, subject, experience, salary) in enumerate(faculty_data):
        cursor.execute(
            "INSERT INTO faculty (id, name, assigned_subject, experience, salary) VALUES (?, ?, ?, ?, ?)",
            (i + 1, name, subject, experience, salary)
        )

    conn.commit()
    cursor.execute("SELECT * FROM faculty")
    rows = cursor.fetchall()
    df_faculty = pd.DataFrame(rows, columns=['id', 'name', 'assigned_subject', 'experience', 'salary'])
    conn.close()
    return df_faculty

faculty_data_df = create_faculty_database()
display(faculty_data_df)

"""Here is the head of the newly created faculty database table.

### Calculate faculty salaries based on student enrollment
"""

# Calculate the number of students enrolled in each course
student_enrollment_counts = new_student_data['course'].value_counts().reset_index()
student_enrollment_counts.columns = ['course', 'num_students']
display(student_enrollment_counts)

# Merge faculty data with student enrollment counts to get the number of students per assigned subject
faculty_data_df_updated = pd.merge(
    faculty_data_df,
    student_enrollment_counts,
    left_on='assigned_subject',
    right_on='course',
    how='left'
)

# Fill NaN values for 'num_students' with 0 (if a subject has no enrolled students)
faculty_data_df_updated['num_students'] = faculty_data_df_updated['num_students'].fillna(0).astype(int)

# Calculate new salary: (number of students enrolled * 500)
faculty_data_df_updated['salary'] = faculty_data_df_updated['num_students'] * 500

# Drop the 'course' and 'num_students' columns as they are no longer needed in the final faculty dataframe
faculty_data_df_updated = faculty_data_df_updated.drop(columns=['course', 'num_students'])

display(faculty_data_df_updated)

"""### Join Student and Faculty Data"""

merged_data = pd.merge(
    new_student_data,
    faculty_data_df_updated,
    left_on='course',
    right_on='assigned_subject',
    how='inner'
)

# Display the first few rows of the merged data
display(merged_data.head())
