# -*- coding: utf-8 -*-
"""Web Scraping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fg4Y-y_3zZHwLhn7EtFENeMRQJxMACmI
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://books.toscrape.com/"

response = requests.get(url)

soup = BeautifulSoup(response.content, "html.parser")

books = soup.find_all("article", class_="product_pod")
print(books[0])
data = []

for book in books:
  title = book.h3.a["title"]
  price = book.find("p", class_="price_color").text

  data.append({
      "title": title,
      "price": price
  })

df = pd.DataFrame(data)

print(df.head())

df["price"] = df["price"].str.replace("£", "")

df["price"] = df["price"].astype(float)

mean_price = df["price"].mean()

print("Mean Price:", mean_price)

books_equal_mean = df[df["price"] == mean_price]

print(books_equal_mean)

books_near_mean = df[ (df["price"] >= mean_price - 2) & (df["price"] <= mean_price + 2) ]

print(books_near_mean)

q: List the top rated books in the website in the range or 5 star and 4 star


q=: list the books having the lowest score of one start_ipython

q : list the books of bottom 5 price range
